<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<ApplicationIcon>5926.ico</ApplicationIcon>
	</PropertyGroup>
	<ItemGroup>
	  <Content Include="5926.ico" />
	</ItemGroup>
	<ItemGroup>
	  <PackageReference Include="EPPlus" Version="8.5.4" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\..\Сессия 2\AgroControl.API\AgroControl.API\AgroControl.API.csproj" />
	</ItemGroup>
</Project>